on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     repo:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  PixelDraw:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      CLIP:
        type: dataset
        with:
          ref: openai-clip-repo
      TT: 
        type: dataset
        with:
          ref: taming-transformers-repo
      DIFFVG: 
        type: dataset
        with:
          ref: diffvg-repo
      CLIPIT: 
        type: dataset
        with:
          ref: clipit-repo
    outputs:
      pixels:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
      
        #Copy repo to main dir
        cp -R /inputs/repo /

        pip install ftfy regex tqdm omegaconf pytorch-lightning
        pip install kornia
        pip install imageio-ffmpeg   
        pip install einops
        pip install torch-optimizer
        pip install easydict
        pip install braceexpand
        pip install git+https://github.com/pvigier/perlin-numpy

        # ClipDraw deps
        pip install svgwrite
        pip install svgpathtools
        pip install cssutils
        pip install numba
        pip install torch-tools
        pip install visdom

        # Install DiffVG
        cp -R /inputs/DIFFVG /DIFFVG
        cd /DIFFVG
        git submodule update --init --recursive
        python setup.py install
        cd /
        
        ls -la
        python pixeldraw.py

        #   --result-dir=/outputs/generatedFaces
      image: nvcr.io/nvidia/pytorch:21.02-py3
