on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     repo:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  PixelDraw:
    resources:
      instance-type: V100
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      CLIP:
        type: dataset
        with:
          ref: openai-clip-repo
      TT: 
        type: dataset
        with:
          ref: taming-transformers-repo
      #       DIFFVG: 
      #         type: dataset
      #         with:
      #           ref: diffvg-repo
      CLIPIT: 
        type: dataset
        with:
          ref: clipit-repo
    outputs:
      pixels:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        #Copy repo to main dir
        cd /
        cp -R /inputs/CLIP /CLIP
        cp -R /inputs/TT /taming-transformers
        git clone https://github.com/ViktorAlm/diffvg
        ls

        cp -R /inputs/CLIPIT /clipit
        cp -R /inputs/repo/pixeldraw.py /pixeldraw.py

        # Pytorch pinned version
        # pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
        # pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
        
        # Regular deps
        pip install ftfy regex tqdm omegaconf pytorch-lightning
        pip install kornia
        pip install imageio-ffmpeg   
        pip install einops
        pip install torch-optimizer
        pip install easydict
        pip install braceexpand
        pip install git+https://github.com/pvigier/perlin-numpy

        # ClipDraw deps
        pip install svgwrite
        pip install svgpathtools
        pip install cssutils
        pip install numba
        pip install torch-tools
        pip install visdom

        # Install DiffVG
        cd /diffvg
        git submodule update --init --recursive
        python setup.py install
        cd ..
        
        CUDA_VISIBLE_DEVICES=0 python pixeldraw.py

        ls -la

        # cp output.png /outputs/pixels/output.png
        
      image: nvcr.io/nvidia/pytorch:21.03-py3
