on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
     repo:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  PixelDraw:
    resources:
      instance-type: P6000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      CLIP:
        type: dataset
        with:
          ref: openai-clip-repo
      TT: 
        type: dataset
        with:
          ref: taming-transformers-repo
      #       DIFFVG: 
      #         type: dataset
      #         with:
      #           ref: diffvg-repo
      CLIPIT: 
        type: dataset
        with:
          ref: clipit-repo
    outputs:
      pixels:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-     
        #Copy repo to main dir
        cd /
        cp -R /inputs/CLIP /CLIP
        cp -R /inputs/TT /taming-transformers
        cp -R /inputs/CLIPIT /clipit
        cp -R /inputs/repo/pixeldraw.py /pixeldraw.py

        CUDA_VISIBLE_DEVICES=0 python pixeldraw.py

        #         cd clipit
        #         python3 clipit.py \
        #           --use_pixeldraw True \
        #           --prompt 'Beirut skyline' \
        #           --output test1.png

        cp output.png /outputs/pixels
        
      image: paperspace/clip-pixeldraw
